golioth/reference-design-template

west.yml
Use publicly available https for cloning dependencies:
* golioth-zephyr-boards
* libostentus
=> west.yml: use https instead of ssh

.github/workflows/build_ncs.yml
I've been working on GHA as a side project and think it would be useful to add prebuilt binaries automatically to reference designs. Some background and design designs:
* Separate yml files means we can target different flavors of RTOSes and/or different toolchains (ex. build_ncs.yml)
* Runs on `pushes` to main, semver tags or PRs
* Runs in a VM for speed
* Runs a test matrix across target Zephyr SDKs and boards
* Uses board name as binary name. This is to keep consistent names across build for later automation
* Bundles `.bin` and `.elf` in zip with a unique name per run
Future enhancement planned are using `git describe` in ZIP name, manual running of actions & Containers for more reproducible builds.
Closes #53
=> Prebuilt binaries using GitHub Actions

CHANGELOG.md, src/app_work.c
Not a common scenario, but I tried building for the `aludel_mini_v1_sparkfun9160` board with `CONFIG_LIB_OSTENTUS=n` and found a build error. This PR fixes the build error by ensuring that `CONFIG_LIB_OSTENTUS=y` before trying to set Ostentus slides.
=> Ensure Ostentus is enabled before setting slides

src/battery_monitor/battery.c
Check for an active connection to Golioth before trying to stream battery readings from read_and_report_battery()
=> battery_monitor: only stream if connected

README.rst
The network info code was recently converted to a module and pulled in as a library by west.yml. This commit documents its addition as an external library.
=> README: document zephyr-network-info library

src/main.c
This commit fixes a typo in the Kconfig symbol for the Golioth sample in the main.c file. The symbol should be "CONFIG_GOLIOTH_SAMPLE_COMMON" instead of "CONFIG_GOLIOTH_SAMPLES_COMMON".
=> main: Fix typo in Kconfig symbol for Golioth sample

.github/workflows/build_zephyr.yml
Small update to use the newer Docker Hub images. Everything works the same and tested [here](https://github.com/beriberikix/reference-design-template/actions/runs/6806285964).
=> Use public Docker Hub image

.github/workflows/build_zephyr.yml
Previously `west init` was always checking out the default branch (`main`) instead of the reference or SHA for the GHA event. This PR changes the checkout process to use `actions/checkout@v4` to checkout the reference or SHA for the GHA event, and then initializes the west workspace using the local repo.
=> Ensure west init uses the correct manifest revision in GHA

src/app_state.c
This err variable must be initializated to 0 to avoid triggering an error message when there has been no error. This reverts [a change made during the migration](https://github.com/golioth/reference-design-template/pull/72#discussion_r1496607462).
=> state: initialize err var to zero

src/app_settings.c
When the LOOP_DELAY_S setting is updated, we need to wake the main thread which is currently sleeping based on the old delay value. This means you will have a sensor reading every time a new setting is received, but the point is for new setting to immediately take effect.
=> settings: wake main thread after updating delay

CHANGELOG.md, CMakeLists.txt, src/app_sensors.c, src/app_sensors.h, src/app_state.c, src/battery_monitor/battery.c, src/main.c
The app_work.c/h files are mainly used for reading sensor data and sending on Golioth Stream. Changing the name to app_sensors.c/h will help users understand the purpose of the file.
=> app_work: rename to app_sensors

prj.conf, west.yml
Update Golioth to v0.11.0 and increase RPC return length.
Resolves #87
=> Fix truncated network info

west.yml
Update network info library for better zcbor encoding and more useful error messages.
=> network info: update version to newest release v1.1.1

CHANGELOG.md, README.rst, boards/aludel_elixir_ns.overlay, west.yml
In addition to adding build instructions for the Aludel Elixir board, this also updates the README build instructions to default to the nRF9160 DK board (since most customers don't have access to the Golioth boards).
There is a final commit in the series that fixes some of the CHANGELOG formatting to match the https://keepachangelog.com formatting.
=> Upgrade golioth-zephyr-boards dependency to v1.2.0

boards/aludel_elixir_ns.conf, boards/aludel_elixir_ns.overlay, boards/aludel_mini_v1_sparkfun9160_ns.conf, boards/aludel_mini_v1_sparkfun9160_ns.overlay, src/app_sensors.c, src/main.c, west.yml
libostentus is now a Zephyr driver. Update the module version and change all API calls to match the driver syntax. Add reset and firmware version read when app first runs.
resolves https://github.com/golioth/devrel-issue-tracker/issues/442
=> libostentus: update to v2.0.0

.github/workflows/build_zephyr.yml
We need to substitute forward-slash for underscore when naming artifacts for the new Zephyr board names. The regex approach taken fails when using sh but will pass when the workflow is instructed to use bash.
=> use bash instead of sh so substitutions don't fail

src/app_sensors.c, src/battery_monitor/battery.c
When using LTE, we may start fetching sensor readings before a connection is established with Golioth. Readings can be shown on a local display during this period, but attempting to send to Golioth will fail. This updates the sensor reading streaming, which is just a counter in this case, to only attempt to stream readings to Golioth when connected. This mirrors the behavior of the battery monitor.
(ref for rationale on not blocking until connected: https://github.com/golioth/reference-design-template/pull/72/files#r1489688622)
=> app_sensors: only stream sensor data if connected

.github/workflows/build_zephyr.yml, .github/workflows/release.yml
The new version of upload artifact disallows repeat upload to the same directory. Instead, artifacts should be uploaded using unique names, then gathered into a single archive using the merge and pattern parameters.
=> workflows: bump action-upload to v4

README.rst
Add ecdsa to the pip install command. This package is needed since Golioth Firmware SDK v0.16.0 (probably part of NCS v2.8.0 but unconfirmed). Unfortunately the Zephyr requirements.txt does not include this package.
=> README: add python ecdsa package

README.md
- add overview of functionality
- add a supported hardware overview
- move Golioth Features above Local set up
- update LightDB Stream and LightDB State
- Separate Stream from State
- Add Stream example JSON
- Add LightDB State Example JSON
- Clarify LightDB State functionality
- update OTA instructions for Packages/Cohorts/Deployments
- Move pipelines higher in the document
- Reference the pipelines section from the Stream section
- Move hardware variants lower in the document
- Simplify the hardware variants section
- rename opening section
- make all headings after the first subheadings
- properly style admonitions for GitHub
- add section for additional sensors/components
- remove hardware variations sections
- add mention of use cases and link to projects site
- add section for …
=> README: overhaul for uniformity
